data class DataPoint(
    val mes: Double,
    val dia: Double,
    val year: Double,
    val hora: Double,
    val impresiones: Double,
    val alcance: Double,
    val comentarios: Double,
    val compartidos: Double,
    val clics: Double,
    val reacciones: Double)